### ISSUE TITLE
hard-coded/default password

### ISSUE THREAD

**Issue by bodik** [covid19cz/po-app#19]
https://github.com/covid19cz/po-app/blob/64eab8e50dcd69967b8b3c7e08cd9a1ae059687b/be/api/po-app/src/main/resources/application.yaml#L12

https://github.com/covid19cz/po-app/blob/64eab8e50dcd69967b8b3c7e08cd9a1ae059687b/be/api/po-app/src/main/resources/application.yaml#L36

advisory:

* remove default/hard-coded credentials
* https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password

**Comment by vrehor** [comment]
To je pro lokální vývoj, to snad nevadí, né? V produkci je to kompletně jiné
