### ISSUE TITLE
V zadosti o otestovani se nedostanu na druhy krok.

### ISSUE THREAD

**Issue by Betlista** [covid19cz/po-app#24]
vyplnim povinne udaje na http://localhost:3000/app/123/contact-details a pres "POKRACOVAT" me to nepusti dal...

**Comment by vaclajon** [comment]
123 je neplatny identifikator uzivatele. Jak pridam autorizaci, zacne nam to fungovat. Pro otestovani stranek staci zalozit uzivatele, misto 123 dat jeho uid a melo by to fungovat :)
